# Generated by Django 4.0.4 on 2022-05-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.BooleanField()),
                ('burger', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='palce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ral.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='palce',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ral.palce'),
        ),
    ]
